import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./SessionProvider";
import Header from "@/components/Header";
import { Providers } from "./providers";

const plusJakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={plusJakarta.className}>
        <SessionProvider session={session}>
          <Providers>
            <Header />
            <main className="bg-veryDarkGrey">{children}</main>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
